### PR TITLE
Trivial garbage

### PR DESCRIPTION
**Pull request by rpgoldman**
Ugur, will you please review this merge request?  It replaces our hand-coded calls to `GC` with their very complicated (and seemingly buggy) reader conditionals.  I checked and it passes all the tests.

If you do think it's good, feel free to do a "squash merge" and turn this into just one commit on `master`.

Thanks!

### CODE REVIEW

**Comment by ukuter** [comment]
Just FYI -- you probably received a notification as well but I squashed your commits and merged them back on the master.

Best,
Ugur.

**Comment by rpgoldman** [comment]
Thanks, Ugur.  I have a couple of other patches from people, and then I propose to make Shop3 3.0.1 a release!

**Comment by lispm** [comment]
The function find-plans in shop3/shop3.lisp now might need to declare:

`(declare (ignorable gc))`

Otherwise an implementation not in the  `#+(or ccl allegro sbcl clisp abcl ecl)` will warn about unused variable GC.

**Comment by rpgoldman** [comment]
> The function find-plans in shop3/shop3.lisp now might need to declare:
> 
> `(declare (ignorable gc))`
> 
> Otherwise an implementation not in the `#+(or ccl allegro sbcl clisp abcl ecl)` will warn about unused variable GC.

Thanks for this, but we are dropping that code in place of simply using `trivial-garbage` to perform the task.  Obviously, maintaining all those reader conditionals is a task too much for us to do correctly!

**Pull request merged**
